---
abstract: 'Collect documentation for subroutines'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Documentation
provides:
  Sub::Documentation:
    file: lib/Sub/Documentation.pm
    version: 1.100880
  Sub::Documentation::Attributes:
    file: lib/Sub/Documentation/Attributes.pm
    version: 1.100880
requires:
  Attribute::Handlers: 0
  Carp: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Differences: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Sub-Documentation
  homepage: http://search.cpan.org/dist/Sub-Documentation/
  repository: http://github.com/hanekomu/Sub-Documentation
version: 1.100880
